if(WIN32)
  find_program(CMAKE_C_COMPILER clang-cl REQUIRED)
  find_program(CMAKE_CXX_COMPILER clang-cl REQUIRED)
  find_program(CMAKE_LINKER lld-link REQUIRED)
  find_program(CMAKE_AR llvm-lib REQUIRED)
  set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
  set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)
  set(VSWHERE "$ENV{ProgramFiles\(x86\)}/Microsoft Visual Studio/Installer/vswhere.exe")
  execute_process(COMMAND "${VSWHERE}" -latest -products * -property installationPath OUTPUT_VARIABLE VS_ROOT OUTPUT_STRIP_TRAILING_WHITESPACE)
  file(GLOB VC_VERSIONS "${VS_ROOT}/VC/Tools/MSVC/*")
  list(SORT VC_VERSIONS COMPARE NATURAL ORDER DESCENDING)
  list(GET VC_VERSIONS 0 VC_ROOT)
  get_filename_component(SDK_ROOT "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10]" ABSOLUTE)
  file(GLOB SDK_VERSIONS "${SDK_ROOT}/Include/10.*")
  list(SORT SDK_VERSIONS COMPARE NATURAL ORDER DESCENDING)
  list(GET SDK_VERSIONS 0 SDK_INCLUDE)
  get_filename_component(SDK_VERSION "${SDK_INCLUDE}" NAME)
  set(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "${VC_ROOT}/include;${SDK_INCLUDE}/ucrt;${SDK_INCLUDE}/shared;${SDK_INCLUDE}/um;${SDK_INCLUDE}/winrt")
  set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES "${CMAKE_C_STANDARD_INCLUDE_DIRECTORIES}")
  set(LIB_PATHS "/libpath:\"${VC_ROOT}/lib/x64\" /libpath:\"${SDK_ROOT}/Lib/${SDK_VERSION}/ucrt/x64\" /libpath:\"${SDK_ROOT}/Lib/${SDK_VERSION}/um/x64\"")
  set(CMAKE_EXE_LINKER_FLAGS_INIT "${LIB_PATHS}")
  set(CMAKE_SHARED_LINKER_FLAGS_INIT "${LIB_PATHS}")
  find_program(CMAKE_RC_COMPILER rc HINTS "${SDK_ROOT}/bin/${SDK_VERSION}/x64" REQUIRED)
  find_program(CMAKE_MT mt HINTS "${SDK_ROOT}/bin/${SDK_VERSION}/x64" REQUIRED)
else()
  find_program(CMAKE_C_COMPILER clang REQUIRED)
  find_program(CMAKE_CXX_COMPILER clang++ REQUIRED)
endif()