# vision.cpp and stable-diffusion.cpp require different GGML revisions. Keep
# vision's GGML private to its DLL, with only our C adapter crossing the boundary.
include(ExternalProject)
set(TEXEL_VISION_BINARY_DIR "${CMAKE_BINARY_DIR}/vision")
set(TEXEL_VISION_LIBRARY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_SHARED_LIBRARY_PREFIX}texel-vision${CMAKE_SHARED_LIBRARY_SUFFIX}")
set(TEXEL_VISION_IMPLIB "${TEXEL_VISION_BINARY_DIR}/lib/${CMAKE_IMPORT_LIBRARY_PREFIX}texel-vision${CMAKE_IMPORT_LIBRARY_SUFFIX}")
set(TEXEL_VISION_ARGS)
foreach(setting CMAKE_TOOLCHAIN_FILE CMAKE_MAKE_PROGRAM CMAKE_C_COMPILER CMAKE_CXX_COMPILER CMAKE_MSVC_RUNTIME_LIBRARY
        CMAKE_C_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_EXE_LINKER_FLAGS_MINSIZEREL CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL
        GGML_NATIVE GGML_AVX GGML_AVX2 GGML_FMA GGML_F16C GGML_AVX512)
    if(DEFINED ${setting})
        list(APPEND TEXEL_VISION_ARGS "-D${setting}=${${setting}}")
    endif()
endforeach()
ExternalProject_Add(texel-vision-build
    SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/vision"
    BINARY_DIR "${TEXEL_VISION_BINARY_DIR}"
    DOWNLOAD_COMMAND ""
    UPDATE_COMMAND ""
    CMAKE_ARGS ${TEXEL_VISION_ARGS}
        "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
        "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}"
        "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}"
        "-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=${TEXEL_VISION_BINARY_DIR}/lib"
        "-DVISP_VULKAN=${IMGED_VULKAN}"
    BUILD_COMMAND "${CMAKE_COMMAND}" --build <BINARY_DIR> --config $<CONFIG> --target visioncpp --parallel 2
    BUILD_BYPRODUCTS "${TEXEL_VISION_LIBRARY}" "${TEXEL_VISION_IMPLIB}"
    BUILD_ALWAYS TRUE
    INSTALL_COMMAND ""
)
add_library(texel-vision SHARED IMPORTED GLOBAL)
set_target_properties(texel-vision PROPERTIES
    IMPORTED_LOCATION "${TEXEL_VISION_LIBRARY}"
    IMPORTED_IMPLIB "${TEXEL_VISION_IMPLIB}"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/vision"
)
add_dependencies(texel-vision texel-vision-build)
